import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { songId } = await req.json();
    if (!songId) return Response.json({ error: 'songId is required' }, { status: 400 });

    const song = await base44.entities.Song.get(songId);
    if (!song) return Response.json({ error: 'Song not found' }, { status: 404 });

    const content = `${song.title}\n${'='.repeat(song.title.length)}\n\n${song.car_make ? `Car: ${song.car_color ? song.car_color + ' ' : ''}${song.car_make}\n` : ''}${song.location ? `Last seen: ${song.location}\n` : ''}${song.genre ? `Genre: ${song.genre}\n` : ''}${song.mood ? `Mood: ${song.mood}\n` : ''}\n${'─'.repeat(40)}\n\n${song.lyrics}\n\n${'─'.repeat(40)}\nGenerated by Car Song Generator`;

    return new Response(content, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="${song.title.replace(/[^a-z0-9]/gi, '_')}.txt"`,
      },
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});