import React, { useState } from "react";
import { motion } from "framer-motion";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Copy, Check, RotateCcw, Music2, Mic2, Download, Volume2, Loader2, Share2, ImageIcon } from "lucide-react";
import { toast } from "sonner";
import { base44 } from "@/api/base44Client";

const genreEmojis = {
  pop: "🎤", country: "🤠", "hip-hop": "🎙️", rock: "🎸",
  gospel: "🙏", "r&b": "🎶", metal: "🤘", jazz: "🎷",
};

export default function SongDisplay({ song, onNewSong }) {
  const [copied, setCopied] = useState(false);
  const [generatingAudio, setGeneratingAudio] = useState(false);
  const [audioUrl, setAudioUrl] = useState(song.audio_url || null);
  const [genSeconds, setGenSeconds] = useState(0);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(`${song.title}\n\n${song.lyrics}`);
    setCopied(true);
    toast.success("Lyrics copied!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleGenerateAudio = async () => {
    setGeneratingAudio(true);
    setGenSeconds(0);
    const timer = setInterval(() => setGenSeconds(s => s + 1), 1000);

    try {
      const carDesc = [song.car_year, song.car_make].filter(Boolean).join(" ");

      // Start the prediction
      const startRes = await base44.functions.invoke("generateMusic", { action: "start", genre: song.genre, carDesc, lyrics: song.lyrics });
      if (startRes.data?.error) throw new Error(startRes.data.error);

      // If it completed instantly, use the audio_url directly
      if (startRes.data?.status === "succeeded" && startRes.data?.audio_url) {
        setAudioUrl(startRes.data.audio_url);
        if (song.id) await base44.entities.Song.update(song.id, { audio_url: startRes.data.audio_url });
        toast.success("Music ready!");
        return;
      }

      const predictionId = startRes.data?.prediction_id;
      if (!predictionId) throw new Error("No prediction ID returned. Response: " + JSON.stringify(startRes.data));

      // Poll until done (up to ~3 minutes)
      let attempts = 0;
      while (attempts < 60) {
        await new Promise(r => setTimeout(r, 3000));
        attempts++;
        const pollRes = await base44.functions.invoke("generateMusic", { action: "poll", predictionId });
        const data = pollRes.data;
        if (data?.status === "succeeded" && data?.audio_url) {
          setAudioUrl(data.audio_url);
          if (song.id) await base44.entities.Song.update(song.id, { audio_url: data.audio_url });
          toast.success("Music ready!");
          return;
        }
        if (data?.status === "failed") throw new Error(data.error || "Generation failed");
      }

      throw new Error("Music generation timed out");
    } catch (err) {
      toast.error("Music generation failed. Try again.");
      console.error(err);
    } finally {
      clearInterval(timer);
      setGeneratingAudio(false);
    }
  };

  const handleShare = async () => {
    const text = `🎵 "${song.title}" — A custom ${song.genre} song about my ${song.car_year ? song.car_year + " " : ""}${song.car_color ? song.car_color + " " : ""}${song.car_make}!\n\nGenerated by Car Song Generator`;
    if (navigator.share) {
      await navigator.share({ title: song.title, text });
    } else {
      await navigator.clipboard.writeText(text);
      toast.success("Share text copied to clipboard!");
    }
  };

  const photos = [
    { key: "photo_front", label: "Front" },
    { key: "photo_side", label: "Side" },
    { key: "photo_rear", label: "Rear" },
    { key: "photo_interior", label: "Interior" },
  ];

  const hasPhotos = photos.some((p) => song[p.key]);

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.97, y: 10 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-5"
    >
      {/* AI Car Photos */}
      {hasPhotos && (
        <div>
          <div className="flex items-center gap-2 mb-3">
            <ImageIcon className="w-4 h-4 text-primary" />
            <span className="font-heading text-xs tracking-widest text-primary uppercase">AI Car Photos</span>
          </div>
          <div className="grid grid-cols-2 gap-3">
            {photos.map((p) =>
              song[p.key] ? (
                <div key={p.key} className="relative group rounded-lg overflow-hidden border border-border/50">
                  <img src={song[p.key]} alt={`${p.label} view`} className="w-full h-40 object-cover" />
                  <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-background/80 to-transparent px-3 py-2">
                    <span className="font-heading text-[10px] tracking-widest text-foreground/80 uppercase">{p.label}</span>
                  </div>
                </div>
              ) : (
                <div key={p.key} className="w-full h-40 rounded-lg border border-border/30 bg-card flex items-center justify-center">
                  <div className="text-center">
                    <div className="w-6 h-6 border-2 border-primary/30 border-t-primary rounded-full animate-spin mx-auto mb-2" />
                    <span className="font-heading text-[10px] tracking-widest text-muted-foreground uppercase">{p.label}</span>
                  </div>
                </div>
              )
            )}
          </div>
        </div>
      )}

      {/* Song Card */}
      <Card className="overflow-hidden border-border/60 bg-card shadow-[0_0_40px_rgba(0,200,220,0.1)]">
        {/* Header */}
        <div className="bg-gradient-to-r from-primary/20 via-primary/10 to-transparent border-b border-primary/20 p-6 sm:p-8">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Mic2 className="w-4 h-4 text-primary" />
                <span className="text-primary/70 text-xs font-heading tracking-widest uppercase">Original Song</span>
              </div>
              <h2 className="text-xl sm:text-2xl font-heading font-bold text-foreground leading-tight">
                {song.title}
              </h2>
            </div>
            <Music2 className="w-8 h-8 text-primary/30 flex-shrink-0" />
          </div>
          <div className="flex flex-wrap gap-2 mt-4">
            {song.genre && (
              <Badge className="bg-primary/10 text-primary border-primary/20">
                {genreEmojis[song.genre]} {song.genre}
              </Badge>
            )}
            {song.car_make && (
              <Badge className="bg-primary/10 text-primary border-primary/20">
                🚗 {[song.car_year, song.car_color, song.car_make].filter(Boolean).join(" ")}
              </Badge>
            )}
          </div>
        </div>

        {/* Audio */}
        <div className="px-6 sm:px-8 pt-6">
          {audioUrl ? (
            <div className="bg-primary/5 border border-primary/20 rounded-lg p-4 flex flex-col gap-3">
              <div className="flex items-center gap-2 text-primary text-xs font-heading tracking-widest uppercase">
                <Volume2 className="w-4 h-4" />
                Hear The Song
              </div>
              <audio controls src={audioUrl} className="w-full" />
              <a href={audioUrl} download={`${song.title.replace(/[^a-z0-9]/gi, "_")}.mp3`} target="_blank" rel="noopener noreferrer">
                <Button size="sm" className="bg-primary text-primary-foreground hover:bg-primary/90 font-heading text-xs tracking-wider rounded-sm">
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  Download MP3
                </Button>
              </a>
            </div>
          ) : (
            <Button
              onClick={handleGenerateAudio}
              disabled={generatingAudio}
              className="w-full h-12 bg-primary text-primary-foreground hover:bg-primary/90 font-heading text-xs tracking-widest rounded-sm shadow-[0_0_20px_rgba(0,200,220,0.3)]"
            >
              {generatingAudio ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Generating Music... {genSeconds}s</>
              ) : (
                <><Volume2 className="w-4 h-4 mr-2" />🎵 GENERATE & PLAY MUSIC</>
              )}
            </Button>
          )}
        </div>

        {/* Lyrics */}
        <div className="p-6 sm:p-8">
          <pre className="whitespace-pre-wrap font-body text-base leading-relaxed text-foreground/90">
            {song.lyrics}
          </pre>
        </div>

        {/* Actions */}
        <div className="px-6 sm:px-8 pb-6 sm:pb-8 flex flex-wrap gap-3">
          <Button
            onClick={handleShare}
            variant="outline"
            className="flex items-center gap-2 border-primary/30 text-primary hover:bg-primary/10 rounded-sm"
          >
            <Share2 className="w-4 h-4" />
            Share
          </Button>
          <Button
            onClick={handleCopy}
            variant="outline"
            className="flex items-center gap-2 border-border/60 hover:border-primary/40 rounded-sm"
          >
            {copied ? <Check className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy Lyrics"}
          </Button>
          <Button
            onClick={onNewSong}
            variant="ghost"
            className="flex items-center gap-2 text-muted-foreground hover:text-primary rounded-sm"
          >
            <RotateCcw className="w-4 h-4" />
            New Song
          </Button>
        </div>
      </Card>
    </motion.div>
  );
}